# Generated by Django 4.1.3 on 2022-12-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologist',
            options={'managed': True},
        ),
    ]
