# Generated by Django 4.1.3 on 2022-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_psychologist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='scfhs_file',
            field=models.FileField(db_column='SCFHS_file', upload_to='blog/static/blog/files/'),
        ),
    ]
