# Generated by Django 4.1.3 on 2022-12-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_psychologist_p_code_alter_psychologist_p_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologist',
            options={'managed': False},
        ),
    ]
