# Generated by Django 4.1.3 on 2022-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('pt_phone_no', models.CharField(max_length=13)),
                ('pt_name', models.CharField(max_length=250)),
                ('pt_gender', models.CharField(max_length=6)),
                ('pt_edu_level', models.CharField(max_length=60)),
                ('pt_birth_date', models.DateField()),
                ('pt_code', models.CharField(blank=True, max_length=4, null=True)),
                ('pt_plan', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_result', models.IntegerField(blank=True, null=True)),
                ('test_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
    ]
