# Generated by Django 4.1.4 on 2022-12-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(db_column='diagnosis_ID', primary_key=True, serialize=False)),
                ('diagnosis_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'diagnosis',
                'managed': False,
            },
        ),
    ]
