# Generated by Django 4.1.4 on 2022-12-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychoTest',
            fields=[
                ('test_id', models.AutoField(db_column='test_ID', primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=60)),
                ('description', models.CharField(db_column='Description', max_length=400)),
            ],
            options={
                'db_table': 'psycho_test',
                'managed': False,
            },
        ),
    ]
