# Generated by Django 4.1.4 on 2023-01-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_psychotest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychotest',
            options={'managed': True},
        ),
    ]
