# Generated by Django 4.1.4 on 2023-01-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_psychotest_test_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychotest',
            options={'managed': False},
        ),
    ]
